apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: platform-user-traffic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-streaming-cluster # This tells Strimzi which cluster to attach it to
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824