apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce # "Enforce" means instantly block it. "Audit" would just log a warning.
  rules:
  - name: require-image-tag
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "SECURITY VIOLATION: Using the 'latest' image tag is strictly forbidden. Please specify a version."
      pattern:
        spec:
          containers:
          - image: "!*:latest"